version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/aws"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/aws/us-east-1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/cicd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/infra"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/local"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/wtech-api"
    schedule:
      interval: "weekly"
