gitea:
  admin:
    username: localadmin
    password: password
    email: "local@email.com"
  config:
    REPOSITORY:
      ENABLE_PUSH_CREATE_USER: "true"
      ENABLE_PUSH_CREATE_ORG: "true"
    server:
      HTTP_PORT: 3000
  service:
    http:
      type: NodePort
      nodePort: 30030
    ssh:
      type: NodePort
      nodePort: 30022