version: '3.8'

services:
  web-api:
    build:
      context: .
      dockerfile: ./src/WTech.API/Dockerfile
    container_name: web-api-local
    ports:
      - "8080:8080"
    environment:
      - ASPNET_ENVIRONMENT=Development
    networks:
      - api-network

networks:
  api-network:
    driver: bridge