services:
  web:
    build: .
    ports:
      - "8001:8080"
    develop:
      watch:
        - action: sync+restart
          path: ./src/**/bin/**/net8.0/
          target: /app
      environment:
        - ASPNET_ENVIRONMENT=dev
