apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      nodePort: {{ .Values.api.service.nodePort }}
