apiVersion: v1
kind: Service
metadata:
  name: argo-cd-argocd-server
spec:
  type: {{ .Values.argocd.service.type }}
  ports:
    - port: {{ .Values.argocd.service.port }}
      targetPort: 80
      nodePort: {{ .Values.argocd.service.nodePort }}
  selector:
    app: argo-cd-argocd-server