apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-prometheus-stack-grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: 9090
      nodePort: {{ .Values.grafana.service.nodePort }}
  selector:
    app: prometheus-kube-prometheus-stack-grafana