api:
  replicaCount: 1
  image:
    repository: wtech-api
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

gitea:
  service:
    type: NodePort
    port: 3000
    nodePort: 30001

argocd:
  service:
    type: NodePort
    port: 80
    nodePort: 30002

grafana:
  service:
    type: NodePort
    port: 9090
    nodePort: 30003
