gitea:
  admin:
    username: developer
    password: password
    email: "local@email.com"
  config:
    repository:
      ENABLE_PUSH_CREATE_USER: "true"
      ENABLE_PUSH_CREATE_ORG: "true"
    server:
      HTTP_PORT: 3000

service:
  http:
    type: ClusterIP
    port: 3000
