apiVersion: v1
kind: Service
metadata:
  name: {{ include "ministack.fullname" . }}
  labels:
    {{- include "ministack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "ministack.selectorLabels" . | nindent 4 }}